name: gears
checkpoint: null
device: cuda

kwargs:
  hidden_dim: 128
  num_go_gnn_layers: 2
  num_gene_gnn_layers: 2
  decoder_hidden_size: 32
  uncertainty: false
  num_similar_genes_go_graph: 20
  uncertainty_reg: 1.0
  direction_lambda: 0.15
  coexpression_graph_path: /network/scratch/z/zhangya/shared_resource_perturbflow/state-reproduce/replogle/gears/replogle_coexpression.csv
  go_graph_url: https://dataverse.harvard.edu/api/access/datafile/6934319
  pert_type: chemical
